import {
  School,
  User,
  Student,
  Teacher,
  AttendanceRecord,
  FeeChallan,
  Expense,
  TimetableSlot,
  Assignment,
  AssignmentSubmission,
  Exam,
  ExamResult,
  Invoice,
} from "@/types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alexander Vance",
    email: "alexander@saas-edusphere.io",
    role: "super_admin",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 019-2834",
  },
  {
    id: "user-2",
    name: "Dr. Eleanor Wright",
    email: "principal@apexacademy.edu",
    role: "school_admin",
    schoolId: "school-1",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 342-9102",
  },
  {
    id: "user-3",
    name: "Usman Ali",
    email: "usman.ali@apexacademy.edu",
    role: "teacher",
    schoolId: "school-1",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 782-4911",
  },
  {
    id: "user-4",
    name: "Ayan Ahmed",
    email: "ayan.ahmed@student.apexacademy.edu",
    role: "student",
    schoolId: "school-1",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 890-1234",
  },
];

export const mockSchools: School[] = [
  {
    id: "school-1",
    name: "Apex International Academy",
    code: "AIA-101",
    domain: "apex.edusphere.io",
    logo: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=120&auto=format&fit=crop&q=80",
    adminName: "Dr. Eleanor Wright",
    adminEmail: "principal@apexacademy.edu",
    plan: "Pro",
    status: "Active",
    studentCount: 1420,
    maxStudents: 2000,
    createdAt: "2024-03-15",
    renewalDate: "2027-03-15",
    mrr: 2400,
  },
  {
    id: "school-2",
    name: "Beacon Crest Grammar School",
    code: "BCG-204",
    domain: "beaconcrest.edusphere.io",
    logo: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=120&auto=format&fit=crop&q=80",
    adminName: "Marcus Sterling",
    adminEmail: "admin@beaconcrest.org",
    plan: "Enterprise",
    status: "Active",
    studentCount: 2180,
    maxStudents: 3000,
    createdAt: "2023-08-10",
    renewalDate: "2026-11-10",
    mrr: 4500,
  },
  {
    id: "school-3",
    name: "Horizon Science Collegiate",
    code: "HSC-305",
    domain: "horizonsci.edusphere.io",
    logo: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=120&auto=format&fit=crop&q=80",
    adminName: "Prof. Tariq Jamil",
    adminEmail: "tariq@horizoncollegiate.edu",
    plan: "Starter",
    status: "Active",
    studentCount: 650,
    maxStudents: 800,
    createdAt: "2024-01-20",
    renewalDate: "2027-01-20",
    mrr: 950,
  },
  {
    id: "school-4",
    name: "Silverdale Montessori & Prep",
    code: "SMP-408",
    domain: "silverdale.edusphere.io",
    logo: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=120&auto=format&fit=crop&q=80",
    adminName: "Claire Beauchamp",
    adminEmail: "claire@silverdaleprep.com",
    plan: "Pro",
    status: "Trial",
    studentCount: 420,
    maxStudents: 1000,
    createdAt: "2026-08-15",
    renewalDate: "2026-09-15",
    mrr: 0,
  },
  {
    id: "school-5",
    name: "Oakridge STEM High",
    code: "OSH-502",
    domain: "oakridge.edusphere.io",
    adminName: "Nathaniel Cole",
    adminEmail: "n.cole@oakridgestem.edu",
    plan: "Enterprise",
    status: "Active",
    studentCount: 1850,
    maxStudents: 2500,
    createdAt: "2023-11-05",
    renewalDate: "2026-11-05",
    mrr: 3800,
  },
];

export const mockStudents: Student[] = [
  {
    id: "std-1",
    rollNo: "1042",
    name: "Ayan Ahmed",
    email: "ayan.ahmed@student.apexacademy.edu",
    grade: "Grade 10",
    section: "A",
    gender: "Male",
    dob: "2010-05-14",
    bloodGroup: "O+",
    parentName: "Tariq Ahmed",
    parentPhone: "+1 (555) 431-8890",
    parentEmail: "tariq.ahmed@gmail.com",
    address: "742 Evergreen Terrace, Springfield",
    attendanceRate: 96.5,
    gpa: 3.84,
    status: "Enrolled",
    admissionDate: "2022-09-01",
  },
  {
    id: "std-2",
    rollNo: "1043",
    name: "Fatima Noor",
    email: "fatima.noor@student.apexacademy.edu",
    grade: "Grade 10",
    section: "A",
    gender: "Female",
    dob: "2010-08-22",
    bloodGroup: "B+",
    parentName: "Noor ul Hassan",
    parentPhone: "+1 (555) 776-1289",
    parentEmail: "noor.hassan@outlook.com",
    address: "12 Elm St, Suite 4B",
    attendanceRate: 98.2,
    gpa: 3.96,
    status: "Enrolled",
    admissionDate: "2022-09-01",
  },
  {
    id: "std-3",
    rollNo: "1044",
    name: "Bilawal Shah",
    email: "bilawal.shah@student.apexacademy.edu",
    grade: "Grade 10",
    section: "A",
    gender: "Male",
    dob: "2010-02-18",
    bloodGroup: "A+",
    parentName: "Shahid Shah",
    parentPhone: "+1 (555) 321-4567",
    parentEmail: "shahid.shah@gmail.com",
    address: "88 Pine Avenue",
    attendanceRate: 91.0,
    gpa: 3.45,
    status: "Enrolled",
    admissionDate: "2022-09-01",
  },
  {
    id: "std-4",
    rollNo: "1045",
    name: "Zainab Malik",
    email: "zainab.malik@student.apexacademy.edu",
    grade: "Grade 10",
    section: "A",
    gender: "Female",
    dob: "2010-11-09",
    bloodGroup: "AB+",
    parentName: "Rashid Malik",
    parentPhone: "+1 (555) 654-7890",
    parentEmail: "rashid.malik@corp.com",
    address: "15 Oak Ridge Lane",
    attendanceRate: 94.5,
    gpa: 3.72,
    status: "Enrolled",
    admissionDate: "2022-09-01",
  },
  {
    id: "std-5",
    rollNo: "1046",
    name: "Zaid Khan",
    email: "zaid.khan@student.apexacademy.edu",
    grade: "Grade 10",
    section: "A",
    gender: "Male",
    dob: "2010-04-30",
    bloodGroup: "O-",
    parentName: "Imran Khan",
    parentPhone: "+1 (555) 987-6543",
    parentEmail: "imran.k@yahoo.com",
    address: "24 Maple Boulevard",
    attendanceRate: 88.0,
    gpa: 3.15,
    status: "Enrolled",
    admissionDate: "2023-01-10",
  },
  {
    id: "std-6",
    rollNo: "9021",
    name: "Hira Tariq",
    email: "hira.tariq@student.apexacademy.edu",
    grade: "Grade 9",
    section: "B",
    gender: "Female",
    dob: "2011-03-12",
    bloodGroup: "A-",
    parentName: "Tariq Mahmood",
    parentPhone: "+1 (555) 234-8901",
    parentEmail: "tariq.m@hotmail.com",
    address: "45 Cedar Road",
    attendanceRate: 95.0,
    gpa: 3.88,
    status: "Enrolled",
    admissionDate: "2023-09-01",
  },
  {
    id: "std-7",
    rollNo: "9022",
    name: "Omar Farooq",
    email: "omar.farooq@student.apexacademy.edu",
    grade: "Grade 9",
    section: "B",
    gender: "Male",
    dob: "2011-07-29",
    bloodGroup: "B+",
    parentName: "Farooq Azam",
    parentPhone: "+1 (555) 876-5432",
    parentEmail: "farooq.a@gmail.com",
    address: "99 Birch Crest",
    attendanceRate: 92.4,
    gpa: 3.52,
    status: "Enrolled",
    admissionDate: "2023-09-01",
  },
  {
    id: "std-8",
    rollNo: "1105",
    name: "Mahnoor Qureshi",
    email: "mahnoor.q@student.apexacademy.edu",
    grade: "Grade 11",
    section: "A",
    gender: "Female",
    dob: "2009-09-15",
    bloodGroup: "O+",
    parentName: "Salman Qureshi",
    parentPhone: "+1 (555) 456-7891",
    parentEmail: "salman.q@finance.org",
    address: "102 Highland Terrace",
    attendanceRate: 97.0,
    gpa: 3.91,
    status: "Enrolled",
    admissionDate: "2021-09-01",
  },
  {
    id: "std-9",
    rollNo: "1201",
    name: "Hamza Abbasi",
    email: "hamza.a@student.apexacademy.edu",
    grade: "Grade 12",
    section: "A",
    gender: "Male",
    dob: "2008-12-04",
    bloodGroup: "A+",
    parentName: "Naveed Abbasi",
    parentPhone: "+1 (555) 678-1234",
    parentEmail: "naveed.abbasi@gmail.com",
    address: "50 Walnut Heights",
    attendanceRate: 93.8,
    gpa: 3.68,
    status: "Enrolled",
    admissionDate: "2020-09-01",
  },
  {
    id: "std-10",
    rollNo: "1047",
    name: "Sara Shakeel",
    email: "sara.s@student.apexacademy.edu",
    grade: "Grade 10",
    section: "B",
    gender: "Female",
    dob: "2010-06-19",
    bloodGroup: "B-",
    parentName: "Shakeel Ahmed",
    parentPhone: "+1 (555) 789-2345",
    parentEmail: "shakeel@techgroup.com",
    address: "33 Willow Way",
    attendanceRate: 94.0,
    gpa: 3.60,
    status: "Enrolled",
    admissionDate: "2022-09-01",
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: "tch-1",
    empId: "EMP-2041",
    name: "Usman Ali",
    email: "usman.ali@apexacademy.edu",
    phone: "+1 (555) 782-4911",
    designation: "Senior Master Faculty",
    department: "Mathematics & Physical Sciences",
    qualification: "M.Sc. Applied Mathematics, B.Ed.",
    joinDate: "2021-08-15",
    assignedClasses: [
      { grade: "Grade 10", section: "A", subject: "Mathematics" },
      { grade: "Grade 9", section: "B", subject: "Physics" },
      { grade: "Grade 10", section: "B", subject: "Mathematics" },
    ],
    status: "Active",
  },
  {
    id: "tch-2",
    empId: "EMP-2042",
    name: "Dr. Sarah Khan",
    email: "sarah.khan@apexacademy.edu",
    phone: "+1 (555) 441-2309",
    designation: "Head of Chemistry Department",
    department: "Chemistry",
    qualification: "Ph.D. Organic Chemistry",
    joinDate: "2019-01-10",
    assignedClasses: [
      { grade: "Grade 10", section: "A", subject: "Chemistry" },
      { grade: "Grade 11", section: "A", subject: "Chemistry" },
      { grade: "Grade 12", section: "A", subject: "Advanced Chemistry" },
    ],
    status: "Active",
  },
  {
    id: "tch-3",
    empId: "EMP-2043",
    name: "Farhan Siddiqui",
    email: "farhan.s@apexacademy.edu",
    phone: "+1 (555) 890-4412",
    designation: "Lecturer in English Literature",
    department: "Humanities & Languages",
    qualification: "M.A. English Literature",
    joinDate: "2022-09-01",
    assignedClasses: [
      { grade: "Grade 10", section: "A", subject: "English Literature" },
      { grade: "Grade 9", section: "B", subject: "English Language" },
    ],
    status: "Active",
  },
  {
    id: "tch-4",
    empId: "EMP-2044",
    name: "Ayesha Rehman",
    email: "ayesha.r@apexacademy.edu",
    phone: "+1 (555) 556-7890",
    designation: "Computer Science Faculty",
    department: "Computer Science & AI",
    qualification: "M.S. Computer Science",
    joinDate: "2023-01-15",
    assignedClasses: [
      { grade: "Grade 10", section: "A", subject: "Computer Science" },
      { grade: "Grade 11", section: "A", subject: "Data Science & Python" },
    ],
    status: "Active",
  },
  {
    id: "tch-5",
    empId: "EMP-2045",
    name: "David Sterling",
    email: "david.s@apexacademy.edu",
    phone: "+1 (555) 234-5678",
    designation: "Biology Specialist",
    department: "Biological Sciences",
    qualification: "M.Sc. Molecular Biology",
    joinDate: "2020-03-01",
    assignedClasses: [
      { grade: "Grade 10", section: "A", subject: "Biology" },
      { grade: "Grade 9", section: "B", subject: "General Science" },
    ],
    status: "Active",
  },
];

export const mockTimetable: TimetableSlot[] = [
  // Monday
  { id: "tt-1", day: "Monday", period: 1, startTime: "08:00", endTime: "08:50", grade: "Grade 10", section: "A", subject: "Mathematics", teacherId: "tch-1", teacherName: "Usman Ali", room: "Hall A-102" },
  { id: "tt-2", day: "Monday", period: 2, startTime: "08:50", endTime: "09:40", grade: "Grade 10", section: "A", subject: "Chemistry", teacherId: "tch-2", teacherName: "Dr. Sarah Khan", room: "Lab Chem-1" },
  { id: "tt-3", day: "Monday", period: 3, startTime: "09:40", endTime: "10:30", grade: "Grade 10", section: "A", subject: "English Literature", teacherId: "tch-3", teacherName: "Farhan Siddiqui", room: "Hall A-102" },
  { id: "tt-4", day: "Monday", period: 4, startTime: "11:00", endTime: "11:50", grade: "Grade 10", section: "A", subject: "Computer Science", teacherId: "tch-4", teacherName: "Ayesha Rehman", room: "Lab CS-2" },
  { id: "tt-5", day: "Monday", period: 5, startTime: "11:50", endTime: "12:40", grade: "Grade 10", section: "A", subject: "Biology", teacherId: "tch-5", teacherName: "David Sterling", room: "Lab Bio-1" },
  { id: "tt-6", day: "Monday", period: 6, startTime: "12:40", endTime: "13:30", grade: "Grade 10", section: "A", subject: "Physical Education", teacherId: "tch-6", teacherName: "Coach Miller", room: "Gymnasium" },
  { id: "tt-7", day: "Monday", period: 7, startTime: "13:30", endTime: "14:15", grade: "Grade 10", section: "A", subject: "Library / Study Hall", teacherId: "tch-3", teacherName: "Farhan Siddiqui", room: "Library" },

  // Tuesday
  { id: "tt-8", day: "Tuesday", period: 1, startTime: "08:00", endTime: "08:50", grade: "Grade 10", section: "A", subject: "Chemistry", teacherId: "tch-2", teacherName: "Dr. Sarah Khan", room: "Lab Chem-1" },
  { id: "tt-9", day: "Tuesday", period: 2, startTime: "08:50", endTime: "09:40", grade: "Grade 10", section: "A", subject: "Mathematics", teacherId: "tch-1", teacherName: "Usman Ali", room: "Hall A-102" },
  { id: "tt-10", day: "Tuesday", period: 3, startTime: "09:40", endTime: "10:30", grade: "Grade 10", section: "A", subject: "Computer Science", teacherId: "tch-4", teacherName: "Ayesha Rehman", room: "Lab CS-2" },
  { id: "tt-11", day: "Tuesday", period: 4, startTime: "11:00", endTime: "11:50", grade: "Grade 10", section: "A", subject: "English Literature", teacherId: "tch-3", teacherName: "Farhan Siddiqui", room: "Hall A-102" },
  { id: "tt-12", day: "Tuesday", period: 5, startTime: "11:50", endTime: "12:40", grade: "Grade 10", section: "A", subject: "Mathematics", teacherId: "tch-1", teacherName: "Usman Ali", room: "Hall A-102" },
  { id: "tt-13", day: "Tuesday", period: 6, startTime: "12:40", endTime: "13:30", grade: "Grade 10", section: "A", subject: "Islamic / Moral Studies", teacherId: "tch-7", teacherName: "M. Hashim", room: "Hall A-102" },
  { id: "tt-14", day: "Tuesday", period: 7, startTime: "13:30", endTime: "14:15", grade: "Grade 10", section: "A", subject: "Robotics Club", teacherId: "tch-4", teacherName: "Ayesha Rehman", room: "Makerspace" },

  // Wednesday
  { id: "tt-15", day: "Wednesday", period: 1, startTime: "08:00", endTime: "08:50", grade: "Grade 10", section: "A", subject: "Mathematics", teacherId: "tch-1", teacherName: "Usman Ali", room: "Hall A-102" },
  { id: "tt-16", day: "Wednesday", period: 2, startTime: "08:50", endTime: "09:40", grade: "Grade 10", section: "A", subject: "Physics", teacherId: "tch-1", teacherName: "Usman Ali", room: "Lab Phys-1" },
  { id: "tt-17", day: "Wednesday", period: 3, startTime: "09:40", endTime: "10:30", grade: "Grade 10", section: "A", subject: "Biology", teacherId: "tch-5", teacherName: "David Sterling", room: "Lab Bio-1" },
  { id: "tt-18", day: "Wednesday", period: 4, startTime: "11:00", endTime: "11:50", grade: "Grade 10", section: "A", subject: "Chemistry", teacherId: "tch-2", teacherName: "Dr. Sarah Khan", room: "Lab Chem-1" },
  { id: "tt-19", day: "Wednesday", period: 5, startTime: "11:50", endTime: "12:40", grade: "Grade 10", section: "A", subject: "English Literature", teacherId: "tch-3", teacherName: "Farhan Siddiqui", room: "Hall A-102" },
  { id: "tt-20", day: "Wednesday", period: 6, startTime: "12:40", endTime: "13:30", grade: "Grade 10", section: "A", subject: "Art & Design", teacherId: "tch-8", teacherName: "Elena Rostova", room: "Studio 3" },
  { id: "tt-21", day: "Wednesday", period: 7, startTime: "13:30", endTime: "14:15", grade: "Grade 10", section: "A", subject: "Counseling / Mentorship", teacherId: "tch-1", teacherName: "Usman Ali", room: "Hall A-102" },

  // Thursday
  { id: "tt-22", day: "Thursday", period: 1, startTime: "08:00", endTime: "08:50", grade: "Grade 10", section: "A", subject: "Computer Science", teacherId: "tch-4", teacherName: "Ayesha Rehman", room: "Lab CS-2" },
  { id: "tt-23", day: "Thursday", period: 2, startTime: "08:50", endTime: "09:40", grade: "Grade 10", section: "A", subject: "Mathematics", teacherId: "tch-1", teacherName: "Usman Ali", room: "Hall A-102" },
  { id: "tt-24", day: "Thursday", period: 3, startTime: "09:40", endTime: "10:30", grade: "Grade 10", section: "A", subject: "Chemistry", teacherId: "tch-2", teacherName: "Dr. Sarah Khan", room: "Lab Chem-1" },
  { id: "tt-25", day: "Thursday", period: 4, startTime: "11:00", endTime: "11:50", grade: "Grade 10", section: "A", subject: "English Literature", teacherId: "tch-3", teacherName: "Farhan Siddiqui", room: "Hall A-102" },
  { id: "tt-26", day: "Thursday", period: 5, startTime: "11:50", endTime: "12:40", grade: "Grade 10", section: "A", subject: "History & Geography", teacherId: "tch-9", teacherName: "Jonathan Vance", room: "Hall A-102" },
  { id: "tt-27", day: "Thursday", period: 6, startTime: "12:40", endTime: "13:30", grade: "Grade 10", section: "A", subject: "Biology", teacherId: "tch-5", teacherName: "David Sterling", room: "Lab Bio-1" },
  { id: "tt-28", day: "Thursday", period: 7, startTime: "13:30", endTime: "14:15", grade: "Grade 10", section: "A", subject: "Debate & Model UN", teacherId: "tch-3", teacherName: "Farhan Siddiqui", room: "Auditorium" },

  // Friday
  { id: "tt-29", day: "Friday", period: 1, startTime: "08:00", endTime: "08:50", grade: "Grade 10", section: "A", subject: "Mathematics", teacherId: "tch-1", teacherName: "Usman Ali", room: "Hall A-102" },
  { id: "tt-30", day: "Friday", period: 2, startTime: "08:50", endTime: "09:40", grade: "Grade 10", section: "A", subject: "Physics Lab", teacherId: "tch-1", teacherName: "Usman Ali", room: "Lab Phys-1" },
  { id: "tt-31", day: "Friday", period: 3, startTime: "09:40", endTime: "10:30", grade: "Grade 10", section: "A", subject: "Physics Lab", teacherId: "tch-1", teacherName: "Usman Ali", room: "Lab Phys-1" },
  { id: "tt-32", day: "Friday", period: 4, startTime: "11:00", endTime: "11:50", grade: "Grade 10", section: "A", subject: "Computer Science", teacherId: "tch-4", teacherName: "Ayesha Rehman", room: "Lab CS-2" },
  { id: "tt-33", day: "Friday", period: 5, startTime: "11:50", endTime: "12:40", grade: "Grade 10", section: "A", subject: "Assembly & Awards", teacherId: "tch-2", teacherName: "Dr. Eleanor Wright", room: "Main Auditorium" },
];

export const mockAttendanceRecords: AttendanceRecord[] = [
  { id: "att-1", date: "2026-09-06", studentId: "std-1", studentName: "Ayan Ahmed", rollNo: "1042", grade: "Grade 10", section: "A", status: "Present" },
  { id: "att-2", date: "2026-09-06", studentId: "std-2", studentName: "Fatima Noor", rollNo: "1043", grade: "Grade 10", section: "A", status: "Present" },
  { id: "att-3", date: "2026-09-06", studentId: "std-3", studentName: "Bilawal Shah", rollNo: "1044", grade: "Grade 10", section: "A", status: "Present" },
  { id: "att-4", date: "2026-09-06", studentId: "std-4", studentName: "Zainab Malik", rollNo: "1045", grade: "Grade 10", section: "A", status: "Present" },
  { id: "att-5", date: "2026-09-06", studentId: "std-5", studentName: "Zaid Khan", rollNo: "1046", grade: "Grade 10", section: "A", status: "Absent", remarks: "Sick leave email pending" },
  { id: "att-6", date: "2026-09-06", studentId: "std-6", studentName: "Hira Tariq", rollNo: "9021", grade: "Grade 9", section: "B", status: "Present" },
  { id: "att-7", date: "2026-09-06", studentId: "std-7", studentName: "Omar Farooq", rollNo: "9022", grade: "Grade 9", section: "B", status: "Leave", remarks: "Medical appointment" },
  { id: "att-8", date: "2026-09-06", studentId: "std-8", studentName: "Mahnoor Qureshi", rollNo: "1105", grade: "Grade 11", section: "A", status: "Present" },
  { id: "att-9", date: "2026-09-06", studentId: "std-9", studentName: "Hamza Abbasi", rollNo: "1201", grade: "Grade 12", section: "A", status: "Present" },
  { id: "att-10", date: "2026-09-06", studentId: "std-10", studentName: "Sara Shakeel", rollNo: "1047", grade: "Grade 10", section: "B", status: "Present" },
];

export const mockFeeChallans: FeeChallan[] = [
  {
    id: "fc-101",
    challanNo: "CHL-2026-0901",
    studentId: "std-1",
    studentName: "Ayan Ahmed",
    rollNo: "1042",
    grade: "Grade 10",
    section: "A",
    issueDate: "2026-09-01",
    dueDate: "2026-09-15",
    tuitionFee: 450,
    labFee: 80,
    sportsFee: 40,
    totalAmount: 570,
    status: "Paid",
    paidDate: "2026-09-04",
    paymentMethod: "Stripe Online Portal",
  },
  {
    id: "fc-102",
    challanNo: "CHL-2026-0902",
    studentId: "std-2",
    studentName: "Fatima Noor",
    rollNo: "1043",
    grade: "Grade 10",
    section: "A",
    issueDate: "2026-09-01",
    dueDate: "2026-09-15",
    tuitionFee: 450,
    labFee: 80,
    sportsFee: 40,
    totalAmount: 570,
    status: "Paid",
    paidDate: "2026-09-02",
    paymentMethod: "Bank Wire Transfer",
  },
  {
    id: "fc-103",
    challanNo: "CHL-2026-0903",
    studentId: "std-3",
    studentName: "Bilawal Shah",
    rollNo: "1044",
    grade: "Grade 10",
    section: "A",
    issueDate: "2026-09-01",
    dueDate: "2026-09-15",
    tuitionFee: 450,
    labFee: 80,
    sportsFee: 40,
    totalAmount: 570,
    status: "Pending",
  },
  {
    id: "fc-104",
    challanNo: "CHL-2026-0904",
    studentId: "std-4",
    studentName: "Zainab Malik",
    rollNo: "1045",
    grade: "Grade 10",
    section: "A",
    issueDate: "2026-09-01",
    dueDate: "2026-09-15",
    tuitionFee: 450,
    labFee: 80,
    sportsFee: 40,
    totalAmount: 570,
    status: "Pending",
  },
  {
    id: "fc-105",
    challanNo: "CHL-2026-0855",
    studentId: "std-5",
    studentName: "Zaid Khan",
    rollNo: "1046",
    grade: "Grade 10",
    section: "A",
    issueDate: "2026-08-01",
    dueDate: "2026-08-15",
    tuitionFee: 450,
    labFee: 80,
    sportsFee: 40,
    totalAmount: 570,
    status: "Overdue",
  },
  {
    id: "fc-106",
    challanNo: "CHL-2026-0906",
    studentId: "std-6",
    studentName: "Hira Tariq",
    rollNo: "9021",
    grade: "Grade 9",
    section: "B",
    issueDate: "2026-09-01",
    dueDate: "2026-09-15",
    tuitionFee: 420,
    labFee: 60,
    sportsFee: 30,
    totalAmount: 510,
    status: "Paid",
    paidDate: "2026-09-03",
    paymentMethod: "Credit Card",
  },
];

export const mockExpenses: Expense[] = [
  {
    id: "exp-1",
    title: "Quarterly Science Lab Chemicals & Reagents",
    category: "Lab Equipment",
    amount: 3450,
    date: "2026-09-02",
    paymentMethod: "Bank Transfer",
    approvedBy: "Dr. Eleanor Wright",
    status: "Approved",
  },
  {
    id: "exp-2",
    title: "Campus Central HVAC Servicing & Filter Overhaul",
    category: "Maintenance",
    amount: 1850,
    date: "2026-08-28",
    paymentMethod: "Corporate Card",
    approvedBy: "Marcus Vance",
    status: "Approved",
  },
  {
    id: "exp-3",
    title: "Campus High-Speed Fiber Optics Internet",
    category: "Utilities",
    amount: 980,
    date: "2026-09-01",
    paymentMethod: "Auto Debit",
    approvedBy: "Dr. Eleanor Wright",
    status: "Approved",
  },
  {
    id: "exp-4",
    title: "Faculty & Staff Payroll - August 2026",
    category: "Payroll",
    amount: 48200,
    date: "2026-08-31",
    paymentMethod: "ACH Direct Deposit",
    approvedBy: "Dr. Eleanor Wright",
    status: "Approved",
  },
  {
    id: "exp-5",
    title: "Library Books & Digital Journal Licenses",
    category: "Supplies",
    amount: 1400,
    date: "2026-09-03",
    paymentMethod: "Invoice Net-30",
    approvedBy: "Farhan Siddiqui",
    status: "Pending",
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: "asg-1",
    title: "Quadratic Equations & Parabolic Modeling",
    description: "Solve problem sets 4.1 to 4.5 from the textbook and complete the trajectory modeling worksheet.",
    subject: "Mathematics",
    grade: "Grade 10",
    section: "A",
    teacherId: "tch-1",
    teacherName: "Usman Ali",
    assignedDate: "2026-09-02",
    dueDate: "2026-09-10",
    maxMarks: 50,
    attachmentName: "Math_Quad_Worksheet_Ch4.pdf",
    submissionsCount: 22,
    totalStudents: 28,
  },
  {
    id: "asg-2",
    title: "Thermodynamics & Heat Transfer Experiment",
    description: "Write a comprehensive lab report analyzing the specific heat capacity of unknown metals.",
    subject: "Physics",
    grade: "Grade 9",
    section: "B",
    teacherId: "tch-1",
    teacherName: "Usman Ali",
    assignedDate: "2026-09-03",
    dueDate: "2026-09-12",
    maxMarks: 30,
    attachmentName: "Physics_Lab_Protocol_03.pdf",
    submissionsCount: 15,
    totalStudents: 25,
  },
  {
    id: "asg-3",
    title: "Organic Compounds & Hydrocarbon Nomenclature",
    description: "Diagram the IUPAC structures of branched alkanes and write synthesis mechanisms.",
    subject: "Chemistry",
    grade: "Grade 10",
    section: "A",
    teacherId: "tch-2",
    teacherName: "Dr. Sarah Khan",
    assignedDate: "2026-09-01",
    dueDate: "2026-09-08",
    maxMarks: 40,
    attachmentName: "Chem_Hydrocarbons_Task.pdf",
    submissionsCount: 26,
    totalStudents: 28,
  },
  {
    id: "asg-4",
    title: "Python Data Structures: Dictionaries & Sets",
    description: "Implement a student roster hash table with O(1) search and insert functions.",
    subject: "Computer Science",
    grade: "Grade 10",
    section: "A",
    teacherId: "tch-4",
    teacherName: "Ayesha Rehman",
    assignedDate: "2026-09-04",
    dueDate: "2026-09-14",
    maxMarks: 100,
    attachmentName: "cs_assignment_02.py",
    submissionsCount: 18,
    totalStudents: 28,
  },
];

export const mockSubmissions: AssignmentSubmission[] = [
  {
    id: "sub-1",
    assignmentId: "asg-1",
    studentId: "std-1",
    studentName: "Ayan Ahmed",
    rollNo: "1042",
    submittedDate: "2026-09-05 14:30",
    status: "Graded",
    marksObtained: 48,
    maxMarks: 50,
    feedback: "Exceptional mathematical rigor and clear parabolic graphs! Excellent work.",
  },
  {
    id: "sub-2",
    assignmentId: "asg-1",
    studentId: "std-2",
    studentName: "Fatima Noor",
    rollNo: "1043",
    submittedDate: "2026-09-04 19:15",
    status: "Graded",
    marksObtained: 50,
    maxMarks: 50,
    feedback: "Flawless proofs and bonus challenge problem solved cleanly.",
  },
  {
    id: "sub-3",
    assignmentId: "asg-1",
    studentId: "std-3",
    studentName: "Bilawal Shah",
    rollNo: "1044",
    submittedDate: "2026-09-05 21:00",
    status: "Submitted",
    maxMarks: 50,
  },
  {
    id: "sub-4",
    assignmentId: "asg-1",
    studentId: "std-4",
    studentName: "Zainab Malik",
    rollNo: "1045",
    submittedDate: "2026-09-06 09:12",
    status: "Submitted",
    maxMarks: 50,
  },
  {
    id: "sub-5",
    assignmentId: "asg-1",
    studentId: "std-5",
    studentName: "Zaid Khan",
    rollNo: "1046",
    submittedDate: "",
    status: "Pending",
    maxMarks: 50,
  },
];

export const mockExams: Exam[] = [
  {
    id: "ex-1",
    title: "Fall Midterm Examination 2026: Mathematics",
    type: "Midterm",
    subject: "Mathematics",
    grade: "Grade 10",
    date: "2026-10-15",
    time: "09:00 AM - 12:00 PM",
    duration: "3 Hours",
    room: "Exam Hall A",
    totalMarks: 100,
    passingMarks: 50,
    status: "Upcoming",
  },
  {
    id: "ex-2",
    title: "Fall Midterm Examination 2026: Physics",
    type: "Midterm",
    subject: "Physics",
    grade: "Grade 10",
    date: "2026-10-18",
    time: "09:00 AM - 12:00 PM",
    duration: "3 Hours",
    room: "Exam Hall A",
    totalMarks: 100,
    passingMarks: 50,
    status: "Upcoming",
  },
  {
    id: "ex-3",
    title: "Fall Midterm Examination 2026: Chemistry",
    type: "Midterm",
    subject: "Chemistry",
    grade: "Grade 10",
    date: "2026-10-21",
    time: "09:00 AM - 12:00 PM",
    duration: "3 Hours",
    room: "Exam Hall B",
    totalMarks: 100,
    passingMarks: 50,
    status: "Upcoming",
  },
  {
    id: "ex-4",
    title: "Spring Comprehensive Term Finals: Mathematics",
    type: "Final",
    subject: "Mathematics",
    grade: "Grade 10",
    date: "2026-05-20",
    time: "09:00 AM - 12:00 PM",
    duration: "3 Hours",
    room: "Exam Hall A",
    totalMarks: 100,
    passingMarks: 50,
    status: "Published",
  },
];

export const mockExamResults: ExamResult[] = [
  {
    id: "res-1",
    examId: "ex-4",
    examTitle: "Spring Comprehensive Term Finals: Mathematics",
    studentId: "std-1",
    studentName: "Ayan Ahmed",
    rollNo: "1042",
    grade: "Grade 10",
    section: "A",
    marksObtained: 94,
    totalMarks: 100,
    gradeLetter: "A+",
    gpa: 4.0,
    remarks: "Distinction in Advanced Calculus & Trigonometry",
  },
  {
    id: "res-2",
    examId: "ex-4",
    examTitle: "Spring Comprehensive Term Finals: Chemistry",
    studentId: "std-1",
    studentName: "Ayan Ahmed",
    rollNo: "1042",
    grade: "Grade 10",
    section: "A",
    marksObtained: 88,
    totalMarks: 100,
    gradeLetter: "A",
    gpa: 3.8,
    remarks: "Solid theoretical understanding",
  },
  {
    id: "res-3",
    examId: "ex-4",
    examTitle: "Spring Comprehensive Term Finals: Physics",
    studentId: "std-1",
    studentName: "Ayan Ahmed",
    rollNo: "1042",
    grade: "Grade 10",
    section: "A",
    marksObtained: 91,
    totalMarks: 100,
    gradeLetter: "A+",
    gpa: 4.0,
    remarks: "High aptitude in experimental mechanics",
  },
  {
    id: "res-4",
    examId: "ex-4",
    examTitle: "Spring Comprehensive Term Finals: Computer Science",
    studentId: "std-1",
    studentName: "Ayan Ahmed",
    rollNo: "1042",
    grade: "Grade 10",
    section: "A",
    marksObtained: 96,
    totalMarks: 100,
    gradeLetter: "A+",
    gpa: 4.0,
    remarks: "Top performer in Algorithms",
  },
  {
    id: "res-5",
    examId: "ex-4",
    examTitle: "Spring Comprehensive Term Finals: English Literature",
    studentId: "std-1",
    studentName: "Ayan Ahmed",
    rollNo: "1042",
    grade: "Grade 10",
    section: "A",
    marksObtained: 84,
    totalMarks: 100,
    gradeLetter: "B+",
    gpa: 3.4,
    remarks: "Good critical analysis essays",
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv-2026-081",
    invoiceNo: "INV-ED-9481",
    schoolId: "school-1",
    schoolName: "Apex International Academy",
    plan: "Pro Tier (2000 seats)",
    amount: 2400,
    issueDate: "2026-09-01",
    dueDate: "2026-09-15",
    status: "Paid",
    billingCycle: "Monthly",
  },
  {
    id: "inv-2026-082",
    invoiceNo: "INV-ED-9482",
    schoolId: "school-2",
    schoolName: "Beacon Crest Grammar School",
    plan: "Enterprise Tier (3000 seats)",
    amount: 4500,
    issueDate: "2026-09-01",
    dueDate: "2026-09-15",
    status: "Paid",
    billingCycle: "Monthly",
  },
  {
    id: "inv-2026-083",
    invoiceNo: "INV-ED-9483",
    schoolId: "school-3",
    schoolName: "Horizon Science Collegiate",
    plan: "Starter Tier (800 seats)",
    amount: 950,
    issueDate: "2026-09-01",
    dueDate: "2026-09-15",
    status: "Processing",
    billingCycle: "Monthly",
  },
  {
    id: "inv-2026-084",
    invoiceNo: "INV-ED-9484",
    schoolId: "school-5",
    schoolName: "Oakridge STEM High",
    plan: "Enterprise Tier (2500 seats)",
    amount: 3800,
    issueDate: "2026-08-01",
    dueDate: "2026-08-15",
    status: "Overdue",
    billingCycle: "Monthly",
  },
];
